<script type="text/javascript" src="assets/js/jquery-2.1.0.min.js"></script>
<script type="text/javascript" src="assets/js/json2.min.js"></script>
<script type="text/javascript" src="assets/js/underscore.js"></script>
<script type="text/javascript" src="assets/js/backbone.js"></script>
<script type="text/javascript" src="assets/js/jquery.stickyFooter.js"></script>
<script type="text/javascript" src="assets/js/jquery.defaultText.js"></script>
<script type="text/javascript" src="assets/js/jquery.magnific-popup.min.js"></script>
<script type="text/javascript" src="assets/js/jquery.balloon.min.js"></script>
<script type="text/javascript" src="assets/js/common.js"></script>
<script type="text/javascript" src="assets/js/userAccess.js"></script>
